"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowUp, Sparkles } from "lucide-react";
import { useState } from "react";

const answers: Record<string, string> = {
  "What technologies does Bilal know?": "Bilal works across Next.js, React, TypeScript, Node.js, PostgreSQL, TensorFlow.js, and Gemini API—choosing the right layer for the problem rather than treating a stack as a checklist.",
  "What projects has Bilal built?": "His standout work includes Plant Health Assistant, an AI-powered multilingual plant-care product, and BrewBuddy, a tuned machine-learning price prediction system. He has also shipped full-stack commerce workflows for Hayaa By Noor.",
  "What makes Bilal a strong engineer?": "He combines product curiosity with full-stack execution: clear interfaces, dependable backend flows, and practical AI where it makes the user experience more useful.",
  "What are Bilal's strongest achievements?": "Academic consistency stands out: ranked 1st across three semesters, 2nd across two, a peak SGPA of 9.73, and a Scholarly Excellence Award.",
  "Why does Bilal enjoy building products?": "Because a good product turns a messy real-world need into a clear, dependable experience. Bilal enjoys that bridge—from an idea to something people can actually use."
};

export function AskBilal() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const submit = (value: string) => { const match = Object.keys(answers).find((key) => key.toLowerCase() === value.toLowerCase()); setQuestion(value); setAnswer(match ? answers[match] : "Try one of the suggested questions to explore Bilal's work, technical range, achievements, and product approach."); };
  return <section id="ask" className="scroll-mt-12 bg-[#f8fafd] px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl rounded-[1.75rem] border border-border bg-surface p-6 shadow-[0_2px_8px_rgba(60,64,67,0.13)] sm:p-9"><div className="flex items-start gap-4"><div className="relative flex size-11 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-[#4285f4] via-[#8ab4f8] to-[#34a853] text-white"><Sparkles className="size-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#4285f4]">Ask Bilal</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Get a quick, useful answer.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Explore this profile through a guided conversation.</p></div></div><div className="mt-7 rounded-2xl bg-[#f8fafd] p-4 sm:p-5"><AnimatePresence mode="wait">{answer ? <motion.div key={answer} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl"><p className="text-sm font-medium text-foreground">{question}</p><div className="mt-4 flex gap-3"><Sparkles className="mt-1 size-4 shrink-0 text-[#4285f4]" /><p className="leading-7 text-muted-foreground">{answer}</p></div></motion.div> : <div><p className="text-sm font-medium">What would you like to know?</p><p className="mt-1 text-sm text-muted-foreground">Choose a prompt below or ask your own question.</p></div>}</AnimatePresence></div><div className="mt-5 flex flex-wrap gap-2">{Object.keys(answers).map((item) => <button key={item} onClick={() => submit(item)} className="rounded-full border border-border bg-surface px-3 py-2 text-left text-sm text-muted-foreground transition hover:border-[#4285f4]/40 hover:bg-[#e8f0fe] hover:text-foreground">{item}</button>)}</div><form onSubmit={(event) => { event.preventDefault(); submit(question); }} className="mt-6 flex items-center gap-2 rounded-full border border-border bg-surface px-2 py-2 shadow-[0_1px_2px_rgba(60,64,67,0.12)] focus-within:border-[#4285f4]"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about Bilal's experience or work" className="h-10 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none" /><button className="flex size-10 items-center justify-center rounded-full bg-[#4285f4] text-white transition hover:bg-[#3276df]" aria-label="Ask Bilal"><ArrowUp className="size-4" /></button></form><p className="mt-3 text-center text-xs text-muted-foreground">Responses are based on the profile content on this page.</p></div></section>;
}
